---
title: "AbundanceDivAnalysis_AllMemory_DnSampled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(ggplot2)
library(alakazam)
library(gridExtra)
library(ggsignif)
```

# Import raw data output from clone defining (preprocessing and filtering same as in MIS-C. See https://github.com/LucasiteLab/MIS-C_scRNAseq)

```{r}
# Transfer _final folders to a new Diversity_Analysis Folder
home.dir = '~/Documents/Research/Myocarditis/VDJ/TCR/DiversityAnalysis/changeo_inputs_outputs'
project.folders = c('healthy/healthy_final', 'booster/booster_final', 'myocarditis/myo_final','recovered/recovered_final')
group.mapping = c( 'Y28.2'  =	'HD',
                   'Y28.4'  =	'HD',
                   'Y29.2'  =	'HD',
                   'Y54.4'  =	'HD',
                   'B1'  = 'Booster',
                   'B2'  =	'Booster',
                   'B3'  =	'Booster',
                   'B4'  =	'Booster',
                   'Y165.1'  =	'Carditis',
                   'Y167.1'  =	'Carditis',
                   'Y170.1'  =	'Carditis',
                   'Y172.1'  =	'Carditis',
                   '165.1R'  =	'Recovered',
                   '170.1R'  =	'Recovered',
                   '172.1R'  =	'Recovered')
colors = c('HD'    = '#3498DB',
           'Booster'    = '#9B59B6',
           'Carditis'    = '#E74C3C',
           'Recovered' = '#F5B041')
meta.data = data.frame(matrix(ncol = 3, nrow = 0, dimnames = list(NULL, c("sample", "group", "color"))))

```


```{r}
# Loading data and assigning metadata; use **beta chains** only

raw.data = list()

for (folder in project.folders) {
  parent.folder = file.path(home.dir, folder)
  
  child.folders = list.dirs(path = parent.folder, full.names = F, recursive = F)
  
  print(sprintf('Total %d samples under folder %s', length(child.folders), parent.folder))
  
  # iterate all subfolders
  for (f in child.folders) {
    raw.data[[length(raw.data)+1]] = read.table(file = file.path(parent.folder, f, 'filtered_contig_combined_productive-T.tsv'), 
                                                header = TRUE, sep = '\t', stringsAsFactors = F) %>% filter(locus == "TRB")
    this.group = unname(group.mapping[f]) 
    meta.data[nrow(meta.data)+1, ] = c(f, this.group, unname(colors[this.group]))
    names(raw.data)[length(raw.data)] = f
  }
}

```

# Modifying files and subset on annotation

```{r}
set.seed(1)

# Important annotations


obs <- read.csv('~/Documents/Research/Myocarditis/VDJ/TCR/DiversityAnalysis/annotationinputs_new/gen_annot_CD4_specific.csv')
sample_names <- c('Y28-2', 'Y28-4', 'Y29-2', 'Y54-4', 
                  'B1', 'B2', 'B3', 'B4', 
                  'Y165-1', 'Y167-1', 'Y170-1', 'Y172-1', 
                  'Y165-1R', 'Y170-1R', 'Y172-1R')
obs <- obs %>% filter(sample %in% sample_names)
table(obs$sample)

colnames(obs)[1] <- 'orig.barcode'
barcode <- obs$orig.barcode
vec <- sapply(barcode, function(foo) {paste0(strsplit(foo, split = '-')[[1]][1], 
                                             '-', 
                                             strsplit(foo, split = '-')[[1]][2])})
obs$orig.barcode <- vec

split <- obs %>% group_split(sample, .keep = TRUE)

sample_names_mod <- c('B1', 'B2', 'B3', 'B4', 
                      'Y165.1', '165.1R', 'Y167.1', 
                      'Y170.1', '170.1R', 'Y172.1', '172.1R',
                      'Y28.2', 'Y28.4', 'Y29.2', 'Y54.4')
names(split) <- sample_names_mod
```


```{r}
## Modify raw data to have an orig.barcode column

raw.data.mod <- raw.data

for(i in 1:length(raw.data)){
  seq_id <- raw.data[[i]][,1]
  vec <- sapply(seq_id, function(foo) {strsplit(foo, split = '_')[[1]][1]})
  raw.data.mod[[i]]$orig_barcode <- vec
}

## Create subsetted list
raw.data.subset <- list()
for(i in 1:length(raw.data.mod)){
  raw.data.tmp <- raw.data.mod[[i]]
  name <- names(raw.data.mod)[i]
  donor <- split[[name]]
  donor_barcodes <- donor$orig.barcode
  raw.data.subset[[i]] <- raw.data.tmp %>% filter(orig_barcode %in% donor_barcodes)
  names(raw.data.subset)[i] <- name
}

lapply(raw.data.subset, function(foo) {nrow(foo)})

## Remove Y129.1 and downsample

raw.data.final <- list()

for(i in 1:length(raw.data.subset)){
  barcodes <- raw.data.subset[[i]]$orig_barcode
  if(nrow(raw.data.subset[[i]]) > 164) {
     sampled <- sample(barcodes, 164, replace = FALSE)
  } else {
     sampled <- barcodes
  }
  raw.data.final[[i]] <- raw.data.subset[[i]] %>% filter(orig_barcode %in% sampled)
  names(raw.data.final)[i] <- names(raw.data.subset)[i]
}

raw.data <- raw.data.final
sapply(raw.data, function(foo){nrow(foo)})
```

```{r}
# Calculate Abundance and Diversity using package *alakazam*

## Define function to calculate abundance and diversity

is_outlier = function (x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
}

create_layout = function (start_num, end_num, num_col) {
  len_num = end_num - start_num + 1
  num_row = ceiling(len_num / num_col)
  tmp_vec = rep(NA, num_row * num_col)
  tmp_vec[1:len_num] = seq(start_num, end_num)
  return(matrix(tmp_vec, nrow = num_row, byrow = T))
}

```

```{r}
performCalc = function (sub.data, meta.data, my.ylim=0.1, ds.num=200, extra.ylim=NA) {
  
  # plot cell count and cell type distribution
  cellnum.df = data.frame(sample = meta.data[, 'sample'], cellnum = unlist(lapply(sub.data, nrow)), stringsAsFactors=F)
  print(sprintf('Total %s cells', format(sum(cellnum.df$cellnum), big.mark=",", scientific=F)))
  
  # cell with none cell type will have a empty string as its cell type
  celltype.names = as.character(sort(unique(unlist(lapply(sub.data, function (x) unique(x[['annotation']]))))))
  
  my.data<-numeric()
  for (i in 1:length(sub.data)) {
    if(nrow(sub.data[[i]]) == 0) {
      temp.vect = rep(0, length(celltype.names))
      names(temp.vect) = celltype.names
    } else {
      temp.vect = table(as.character(sub.data[[i]]$annotation))
      temp.vect = temp.vect[celltype.names]
      temp.vect[is.na(temp.vect)] = 0
      names(temp.vect) = celltype.names
      temp.vect= t(as.matrix(temp.vect))[1, ]
    }
    temp.matrix = data.frame(cellnum = temp.vect, celltype = names(temp.vect), sample = rep(meta.data[i, 'sample'], length(temp.vect)))
    my.data = rbind(my.data, temp.matrix)
  }
  
  p1 = ggplot(data = my.data, aes(x = sample, y = cellnum, fill = celltype)) +
  geom_bar(stat = "identity") + theme_classic() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + geom_text(aes(sample, cellnum, label = cellnum, fill = NULL), data = cellnum.df, vjust = -0.25, size = 3) + guides(fill = guide_legend(ncol = 1))
  
  # print('Plot of cell numbers')
  g = grid.arrange(p1, ncol=1)
  
  if (ds.num == 0) {return()}
  
  # calculate abundance and diversity
  abundance.list = list()
  diversity.list = list()
  
  for (i in 1:length(sub.data)) {
    
    if (nrow(sub.data[[i]]) < ds.num) {next}
    
    tmp = estimateAbundance(sub.data[[i]], ci=0.95, nboot=200, clone="clone", uniform=T, progress = F, group = NULL, min_n = ds.num, max_n = ds.num)
    diversity.list[[length(diversity.list)+1]] = alphaDiversity(sub.data[[i]], min_q=0, max_q=2, step_q=1, ci=0.95, nboot=200, clone="clone", uniform=T, group = NULL, min_n = ds.num, max_n = ds.num)
    
    # post-process abundance
    # exclude fake clones, re-ranking
    tmp.abundace = tmp@abundance %>%
      filter(!startsWith(clone, 'U'))
    tmp.abundace$rank = 1:nrow(tmp.abundace)
    
    tmp@abundance = tmp.abundace
    abundance.list[[length(abundance.list)+1]] = tmp
    
    names(abundance.list)[length(abundance.list)] = meta.data[i, 'sample']
    names(diversity.list)[length(diversity.list)] = meta.data[i, 'sample']
  }
  

  
  # plot abundance, each condition is a row
  p.list = list()
  if (!is.na(extra.ylim)) {p2.list = list()}
  
  num.col = 7
  layout.matrix = numeric()
  tmp = c(0)
  
  for (condition in names(colors)) {
    sample.names = meta.data[meta.data['group']==condition, 'sample']
    count = tmp[length(tmp)]
    for (sample.name in sample.names) {
      this.abundance = abundance.list[[sample.name]]
      if (!is.null(this.abundance)) {
        
        # get top 200 clones for ploting
        this.abundance@abundance = this.abundance@abundance[1:200, ]
        
        count = count + 1
        p.list[[length(p.list)+1]] = plotAbundanceCurve(this.abundance, colors=colors[condition], silent = TRUE) + ggtitle(sample.name) + ylim(0, my.ylim)
        if (!is.na(extra.ylim)) {
          p2.list[[length(p2.list)+1]] = plotAbundanceCurve(this.abundance, colors=colors[condition], silent = TRUE) + ggtitle(sample.name) + ylim(0, extra.ylim)
        }
      }
    }
    tmp = c(tmp, count)
    layout.matrix = rbind(layout.matrix, create_layout(tmp[length(tmp)-1]+1, tmp[length(tmp)], num.col))
  }

  # print('Plot abundance curves')
  g = grid.arrange(grobs = p.list, ncol=num.col, layout_matrix=layout.matrix)
  if (!is.na(extra.ylim)) {
    g2 = grid.arrange(grobs = p2.list, ncol=num.col, layout_matrix=layout.matrix)
  }
  # extract diversity
  diversity.matrix = numeric()
  for (i in 1:length(diversity.list)) {
    tmp = as.data.frame(diversity.list[[i]]@diversity)
    tmp[, 'group'] = unname(group.mapping[names(diversity.list)[i]])
    tmp[, 'sample'] = names(diversity.list)[i]
    diversity.matrix = rbind(diversity.matrix, tmp)
  }
  
  
  # plot diversity boxplot
  # and add outlier label
  index.names = c("Richness", "Shannon", "Simpson", "Shannon/Richness", "Simpson/Richness")
  p.list<-list()
  for (i in 1:3) {
    p.list[[i]] = diversity.matrix[diversity.matrix$q==i-1, ] %>%
      group_by(group) %>%
      mutate(outlier = ifelse(is_outlier(d), sample, NA)) %>%
      ggplot(., aes(x = group, y = d, color = group, label = sample)) +
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(position = position_jitter(seed = 1)) +
      labs(x = 'Group', y = index.names[i]) +
      scale_color_manual(values = unname(colors)) +
      scale_x_discrete(limits = names(colors)) +
      theme(legend.position = "none") + 
      geom_text(position = position_jitter(seed = 1), hjust = -0.1, size = 3)
  }
  for (i in 4:5) {
    temp.matrix = diversity.matrix[diversity.matrix$q==i-3, ]
    temp.matrix.1 = diversity.matrix[diversity.matrix$q==0, ]
    temp.matrix[, 'd'] = temp.matrix[, 'd'] / temp.matrix.1[, 'd']
    p.list[[i]] = temp.matrix %>%
      group_by(group) %>%
      mutate(outlier = ifelse(is_outlier(d), sample, NA)) %>%
      ggplot(., aes(x = group, y = d, color = group, label = sample)) +
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(position = position_jitter(seed = 1)) +
      labs(x = 'Group', y = index.names[i]) +
      scale_color_manual(values = unname(colors)) +
      scale_x_discrete(limits = names(colors)) +
      theme(legend.position = "none") +
      geom_text(position = position_jitter(seed = 1), hjust = -0.1, size = 3)
  }
  
  p.list[[6]] = cowplot::get_legend(ggplot(data=temp.matrix, aes(x = group, y = d, color = group, label = sample)) +
      geom_boxplot(outlier.shape = NA) +
      geom_jitter(position = position_jitter(seed = 1)) +
      labs(x = 'Group', y = index.names[i]) +
      scale_color_manual(values = unname(colors)) +
      scale_x_discrete(limits = names(colors))) +
      theme_classic(base_size = 3)
      
  #print('Boxplot of clone alpha diversity')
  do.call('grid.arrange', c(p.list, ncol = 3))
  
  return(list(abundance.list, diversity.matrix, p.list))
}
```


```{r}
# temporary note
sub.raw.data = raw.data
```
 
 
```{r}
## Prepare for output
getCellID = function (abundance, this.data, this.sample, this.condition, num=NA) {
  
  # get top num abundance clones, and add sample and condition infos
  if (is.na(num)) {
    this.abundance = abundance %>%
    mutate(sample = this.sample) %>%
    mutate(condition = this.condition) %>%
    subset(select = -c(group))
  } else {
    this.abundance = abundance[1:num, ] %>%
    mutate(sample = this.sample) %>%
    mutate(condition = this.condition) %>%
    subset(select = -c(group))
  }
  
  
  # outer join
  tmp = merge(x = this.abundance, y = this.data[, c('clone', 'cell_barcode')], by = 'clone', all.x = T)
  
  return(tmp[order(tmp$rank), ])
}

getAllCellID = function (abundance.list, data.list, this.condition, num=NA) {
  
  tmp.matrix = numeric()
  
  for (name in names(abundance.list)) {
    tmp = getCellID(abundance.list[[name]]@abundance, data.list[[name]], name, this.condition, num)
    tmp.matrix = rbind(tmp.matrix, tmp)
  }
  
  return(tmp.matrix)
}

# infos for output
cellid.matrix = numeric()
diversity.matrix = numeric()
```

# Add temporary annotations
```{r}
for(i in 1:length(sub.raw.data)){
  sub.raw.data[[i]]$annotation <- 'All Memory'
}

sub.cells = c('All Memory')
sub.data = lapply(sub.raw.data, function (x) x[(!is.na(x$annotation)) & (x$annotation==sub.cells), ])
x = performCalc(sub.data, meta.data, ds.num = (nrow(sub.raw.data[[1]])-1))

```



```{r}
# output diversity
this.condition = 'All Memory'
x[[2]]$condition = this.condition
diversity.matrix = rbind(diversity.matrix, x[[2]])

## Save results

write.csv(diversity.matrix, file = file.path(home.dir, 'diversity_cd4memory_down.csv'), row.names = F)

```

```{r}
#list of dataframes for pvals
diversity.matrix <- x[[2]]
diversity_list <- list()

for(i in 1:3){
  diversity_list[[i]] <- diversity.matrix[diversity.matrix$q==i-1, ] 
}

for(i in 4:5){
  temp.matrix <- diversity.matrix[diversity.matrix$q==i-3, ]
  temp.matrix.1 <- diversity.matrix[diversity.matrix$q==0, ]
  temp.matrix[, 'd'] <- temp.matrix[, 'd'] / temp.matrix.1[, 'd']
  diversity_list[[i]] <- temp.matrix
}

names(diversity_list) <- c("Richness", "Shannon", "Simpson", "Shannon.Richness", "Simpson.Richness")
```

Significance and Plotting

```{r}
chd_misc_df <- data.frame('pval' = rep(NA, 5),
                          'annotation' = names(diversity_list),
                          'comp.a' = 'Booster',
                          'comp.b' = 'Carditis',
                          'ypos' = c(163, 163, 163, 1, 1))


# Comparisons


for(i in 1:nrow(chd_misc_df)){
  chd_misc_df[i,1] <- wilcox.test(x = diversity_list[[i]][5:8,3],
                        y = diversity_list[[i]][9:12,3],
                        alternative = c("two.sided"), correct = FALSE)$p.value
}

for(i in 1:nrow(chd_misc_df)){
  pval <- chd_misc_df[i,1]
  chd_misc_df[i,1] <- format.pval(as.double(as.character(pval)), digits=1, eps=0.001)
}



for(i in 1:length(diversity_list)){
  x <-  diversity_list[[i]] %>%
  group_by(group) %>%
  mutate(outlier = ifelse(is_outlier(d), sample, NA)) %>%
  ggplot(., aes(x = group, y = d)) +
      geom_boxplot(outlier.shape = NA, lwd=0.75,inherit.aes = FALSE, aes(x = group, y = d, fill = group)) +
      geom_jitter(position = position_jitter(seed = 1), inherit.aes = FALSE, aes(x = group, y = d)) +
      labs(x = 'Group', y = names(diversity_list)[i]) +
      scale_color_manual(values = colors) +
      scale_fill_manual(values = colors) +
      scale_x_discrete(limits = names(colors)) +
      theme_classic(base_size = 14) + 
      theme(legend.position = "none") +
      theme(axis.text.x = element_text(angle = 45, hjust=1)) +
      geom_signif(data = chd_misc_df[i,], inherit.aes = FALSE, 
                  aes(xmin = comp.a, xmax = comp.b, annotations = pval,  
                      y_position = ypos), textsize = 4, vjust = -0.2, manual = TRUE)+
      xlab("")
  ggsave(x, file = paste0(names(diversity_list)[i], '_CD4Memory_', ".pdf"), height = 4.5, width = 4)
}
      
```

